services:

  postgres:
    image: postgres:17
    container_name: ai-job-application-db
    restart: always

    environment:
      POSTGRES_DB: ai_job_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5434:5432"

    volumes:
      - ai_job_postgres_data:/var/lib/postgresql/data

volumes:
  ai_job_postgres_data: